version: '3.8'

services:
  # Main Application Only (without Langfuse)
  langgraph-agenticai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langgraph-agenticai-app
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - STREAMLIT_ENV=production
    volumes:
      - ./src:/app/src
      - ./app.py:/app/app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge